#############################################################################
# Makefile for building: Qt-pac-man.app/Contents/MacOS/Qt-pac-man
# Generated by qmake (3.1) (Qt 6.5.2)
# Project:  Qt-pac-man.pro
# Template: app
# Command: /Users/tuhinsaha/Desktop/qt/6.5.2/macos/bin/qmake -o Makefile Qt-pac-man.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../qt/6.5.2/macos/lib/QtWidgets.framework/Headers -I../qt/6.5.2/macos/lib/QtGui.framework/Headers -I../qt/6.5.2/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../qt/6.5.2/macos/mkspecs/macx-clang -F/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib
QMAKE         = /Users/tuhinsaha/Desktop/qt/6.5.2/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/tuhinsaha/Desktop/qt/6.5.2/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/tuhinsaha/Desktop/qt/6.5.2/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Qt-pac-man1.0.0
DISTDIR = /Users/tuhinsaha/Desktop/Qt-pac-man-master/.tmp/Qt-pac-man1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib
LIBS          = $(SUBLIBS) -F/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = source/game.cpp \
		source/game_object.cpp \
		source/ghost.cpp \
		source/main.cpp \
		source/mainwindow.cpp \
		source/pacman.cpp qrc_resources.cpp \
		moc_game.cpp \
		moc_mainwindow.cpp
OBJECTS       = game.o \
		game_object.o \
		ghost.o \
		main.o \
		mainwindow.o \
		pacman.o \
		qrc_resources.o \
		moc_game.o \
		moc_mainwindow.o
DIST          = ../qt/6.5.2/macos/mkspecs/features/spec_pre.prf \
		../qt/6.5.2/macos/mkspecs/features/device_config.prf \
		../qt/6.5.2/macos/mkspecs/common/unix.conf \
		../qt/6.5.2/macos/mkspecs/common/mac.conf \
		../qt/6.5.2/macos/mkspecs/common/macx.conf \
		../qt/6.5.2/macos/mkspecs/common/sanitize.conf \
		../qt/6.5.2/macos/mkspecs/common/gcc-base.conf \
		../qt/6.5.2/macos/mkspecs/common/gcc-base-mac.conf \
		../qt/6.5.2/macos/mkspecs/common/clang.conf \
		../qt/6.5.2/macos/mkspecs/common/clang-mac.conf \
		../qt/6.5.2/macos/mkspecs/qconfig.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_archive.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_taglib.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_yaml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3drender.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_application_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_common_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_crypto_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_dbus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_intent_client_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_intent_server_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_launcher_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_main_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_manager_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_monitor_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_notification_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_package_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_shared_main_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_window_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_charts.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_coap.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_coap_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_declarativeopcua.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_designer.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_grpc.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_grpc_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_gui.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_help.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifmedia.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifmedia_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifvehiclefunctions.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttracker.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_interfaceframework.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_interfaceframework_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_location.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_location_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_mqtt.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_mqtt_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_network.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_nfc.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opcua.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opcua_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdf.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_png_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioning.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_protobuf.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_protobuf_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_repparser.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensors.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialport.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sql.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svg.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserver.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserver_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserverquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_websockets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webview.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_xml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../qt/6.5.2/macos/mkspecs/features/qt_functions.prf \
		../qt/6.5.2/macos/mkspecs/features/qt_config.prf \
		../qt/6.5.2/macos/mkspecs/macx-clang/qmake.conf \
		../qt/6.5.2/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt/6.5.2/macos/mkspecs/features/exclusive_builds.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/sdk.prf \
		../qt/6.5.2/macos/mkspecs/features/toolchain.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/toolchain.prf \
		../qt/6.5.2/macos/mkspecs/features/default_pre.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/default_pre.prf \
		../qt/6.5.2/macos/mkspecs/features/resolve_config.prf \
		../qt/6.5.2/macos/mkspecs/features/default_post.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/default_post.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/objective_c.prf \
		../qt/6.5.2/macos/mkspecs/features/qml_debug.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/mac.prf \
		../qt/6.5.2/macos/mkspecs/features/warn_on.prf \
		../qt/6.5.2/macos/mkspecs/features/permissions.prf \
		../qt/6.5.2/macos/mkspecs/features/qt.prf \
		../qt/6.5.2/macos/mkspecs/features/resources_functions.prf \
		../qt/6.5.2/macos/mkspecs/features/resources.prf \
		../qt/6.5.2/macos/mkspecs/features/moc.prf \
		../qt/6.5.2/macos/mkspecs/features/unix/opengl.prf \
		../qt/6.5.2/macos/mkspecs/features/uic.prf \
		../qt/6.5.2/macos/mkspecs/features/unix/thread.prf \
		../qt/6.5.2/macos/mkspecs/features/qmake_use.prf \
		../qt/6.5.2/macos/mkspecs/features/file_copies.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/rez.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		../qt/6.5.2/macos/mkspecs/features/testcase_targets.prf \
		../qt/6.5.2/macos/mkspecs/features/exceptions.prf \
		../qt/6.5.2/macos/mkspecs/features/yacc.prf \
		../qt/6.5.2/macos/mkspecs/features/lex.prf \
		Qt-pac-man.pro source/game.h \
		source/gameobject.h \
		source/mainwindow.h source/game.cpp \
		source/game_object.cpp \
		source/ghost.cpp \
		source/main.cpp \
		source/mainwindow.cpp \
		source/pacman.cpp
QMAKE_TARGET  = Qt-pac-man
DESTDIR       = 
TARGET        = Qt-pac-man.app/Contents/MacOS/Qt-pac-man

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/tuhinsaha/Desktop/Qt-pac-man-master/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/tuhinsaha/Desktop/Qt-pac-man-master/Qt-pac-man.pro


include /Users/tuhinsaha/Desktop/qt/6.5.2/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Qt-pac-man.app/Contents/MacOS/Qt-pac-man: ui_mainwindow.h $(OBJECTS)  
	@test -d Qt-pac-man.app/Contents/MacOS/ || mkdir -p Qt-pac-man.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qt-pac-man.pro ../qt/6.5.2/macos/mkspecs/macx-clang/qmake.conf ../qt/6.5.2/macos/mkspecs/features/spec_pre.prf \
		../qt/6.5.2/macos/mkspecs/features/device_config.prf \
		../qt/6.5.2/macos/mkspecs/common/unix.conf \
		../qt/6.5.2/macos/mkspecs/common/mac.conf \
		../qt/6.5.2/macos/mkspecs/common/macx.conf \
		../qt/6.5.2/macos/mkspecs/common/sanitize.conf \
		../qt/6.5.2/macos/mkspecs/common/gcc-base.conf \
		../qt/6.5.2/macos/mkspecs/common/gcc-base-mac.conf \
		../qt/6.5.2/macos/mkspecs/common/clang.conf \
		../qt/6.5.2/macos/mkspecs/common/clang-mac.conf \
		../qt/6.5.2/macos/mkspecs/qconfig.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_archive.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_taglib.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_ext_yaml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3drender.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_application_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_common_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_crypto_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_dbus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_intent_client_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_intent_server_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_launcher_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_main_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_manager_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_monitor_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_notification_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_package_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_shared_main_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_window_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_charts.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_coap.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_coap_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_declarativeopcua.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_designer.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_grpc.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_grpc_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_gui.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_help.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifmedia.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifmedia_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifvehiclefunctions.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttracker.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_interfaceframework.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_interfaceframework_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_location.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_location_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_mqtt.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_mqtt_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_network.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_nfc.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opcua.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opcua_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdf.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_png_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioning.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_protobuf.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_protobuf_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_repparser.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensors.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialport.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sql.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svg.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserver.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserver_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserverquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_websockets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webview.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_xml.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../qt/6.5.2/macos/mkspecs/features/qt_functions.prf \
		../qt/6.5.2/macos/mkspecs/features/qt_config.prf \
		../qt/6.5.2/macos/mkspecs/macx-clang/qmake.conf \
		../qt/6.5.2/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt/6.5.2/macos/mkspecs/features/exclusive_builds.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/sdk.prf \
		../qt/6.5.2/macos/mkspecs/features/toolchain.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/toolchain.prf \
		../qt/6.5.2/macos/mkspecs/features/default_pre.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/default_pre.prf \
		../qt/6.5.2/macos/mkspecs/features/resolve_config.prf \
		../qt/6.5.2/macos/mkspecs/features/default_post.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/default_post.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/objective_c.prf \
		../qt/6.5.2/macos/mkspecs/features/qml_debug.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/mac.prf \
		../qt/6.5.2/macos/mkspecs/features/warn_on.prf \
		../qt/6.5.2/macos/mkspecs/features/permissions.prf \
		../qt/6.5.2/macos/mkspecs/features/qt.prf \
		../qt/6.5.2/macos/mkspecs/features/resources_functions.prf \
		../qt/6.5.2/macos/mkspecs/features/resources.prf \
		../qt/6.5.2/macos/mkspecs/features/moc.prf \
		../qt/6.5.2/macos/mkspecs/features/unix/opengl.prf \
		../qt/6.5.2/macos/mkspecs/features/uic.prf \
		../qt/6.5.2/macos/mkspecs/features/unix/thread.prf \
		../qt/6.5.2/macos/mkspecs/features/qmake_use.prf \
		../qt/6.5.2/macos/mkspecs/features/file_copies.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/rez.prf \
		../qt/6.5.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		../qt/6.5.2/macos/mkspecs/features/testcase_targets.prf \
		../qt/6.5.2/macos/mkspecs/features/exceptions.prf \
		../qt/6.5.2/macos/mkspecs/features/yacc.prf \
		../qt/6.5.2/macos/mkspecs/features/lex.prf \
		Qt-pac-man.pro \
		resources.qrc \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../qt/6.5.2/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../qt/6.5.2/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Qt-pac-man.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../qt/6.5.2/macos/mkspecs/features/spec_pre.prf:
../qt/6.5.2/macos/mkspecs/features/device_config.prf:
../qt/6.5.2/macos/mkspecs/common/unix.conf:
../qt/6.5.2/macos/mkspecs/common/mac.conf:
../qt/6.5.2/macos/mkspecs/common/macx.conf:
../qt/6.5.2/macos/mkspecs/common/sanitize.conf:
../qt/6.5.2/macos/mkspecs/common/gcc-base.conf:
../qt/6.5.2/macos/mkspecs/common/gcc-base-mac.conf:
../qt/6.5.2/macos/mkspecs/common/clang.conf:
../qt/6.5.2/macos/mkspecs/common/clang-mac.conf:
../qt/6.5.2/macos/mkspecs/qconfig.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_ext_archive.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_ext_freetype.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_ext_libpng.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_ext_taglib.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_ext_yaml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3danimation.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dcore.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dextras.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dinput.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dlogic.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquick.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3drender.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_3drender_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_application_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_common_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_crypto_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_dbus_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_intent_client_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_intent_server_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_launcher_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_main_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_manager_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_monitor_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_notification_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_package_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_shared_main_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_appman_window_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_bluetooth.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_charts.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_charts_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_coap.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_coap_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_concurrent.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_core.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_core5compat.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_core_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualization.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_dbus.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_declarativeopcua.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_designer.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_designer_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_grpc.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_grpc_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_gui.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_gui_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_help.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_help_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_httpserver.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_httpserver_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifmedia.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifmedia_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifvehiclefunctions.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttracker.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttracker_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_interfaceframework.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_interfaceframework_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssettings.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_languageserver_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_linguist.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_location.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_location_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_mqtt.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_mqtt_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimedia.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_network.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_network_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_networkauth.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_nfc.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_nfc_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_opcua.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_opcua_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_opengl.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdf.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdf_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfquick.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_png_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioning.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioning_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioningquick.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_printsupport.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_protobuf.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_protobuf_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltest.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3d.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysics.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_repparser.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_repparser_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensors.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensors_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialbus.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialport.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_serialport_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_shadertools.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_sql.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_sql_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachine.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_svg.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_svg_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_testlib.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_texttospeech.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_texttospeech_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_tools_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_uitools.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserver.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserver_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_vncserverquick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webchannel.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginecore.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequick.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_websockets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_websockets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webview.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webview_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webviewquick.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_widgets.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_xml.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_lib_xml_private.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../qt/6.5.2/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../qt/6.5.2/macos/mkspecs/features/qt_functions.prf:
../qt/6.5.2/macos/mkspecs/features/qt_config.prf:
../qt/6.5.2/macos/mkspecs/macx-clang/qmake.conf:
../qt/6.5.2/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../qt/6.5.2/macos/mkspecs/features/exclusive_builds.prf:
../qt/6.5.2/macos/mkspecs/features/mac/sdk.prf:
../qt/6.5.2/macos/mkspecs/features/toolchain.prf:
../qt/6.5.2/macos/mkspecs/features/mac/toolchain.prf:
../qt/6.5.2/macos/mkspecs/features/default_pre.prf:
../qt/6.5.2/macos/mkspecs/features/mac/default_pre.prf:
../qt/6.5.2/macos/mkspecs/features/resolve_config.prf:
../qt/6.5.2/macos/mkspecs/features/default_post.prf:
../qt/6.5.2/macos/mkspecs/features/mac/default_post.prf:
../qt/6.5.2/macos/mkspecs/features/mac/objective_c.prf:
../qt/6.5.2/macos/mkspecs/features/qml_debug.prf:
../qt/6.5.2/macos/mkspecs/features/mac/mac.prf:
../qt/6.5.2/macos/mkspecs/features/warn_on.prf:
../qt/6.5.2/macos/mkspecs/features/permissions.prf:
../qt/6.5.2/macos/mkspecs/features/qt.prf:
../qt/6.5.2/macos/mkspecs/features/resources_functions.prf:
../qt/6.5.2/macos/mkspecs/features/resources.prf:
../qt/6.5.2/macos/mkspecs/features/moc.prf:
../qt/6.5.2/macos/mkspecs/features/unix/opengl.prf:
../qt/6.5.2/macos/mkspecs/features/uic.prf:
../qt/6.5.2/macos/mkspecs/features/unix/thread.prf:
../qt/6.5.2/macos/mkspecs/features/qmake_use.prf:
../qt/6.5.2/macos/mkspecs/features/file_copies.prf:
../qt/6.5.2/macos/mkspecs/features/mac/rez.prf:
../qt/6.5.2/macos/mkspecs/features/mac/asset_catalogs.prf:
../qt/6.5.2/macos/mkspecs/features/testcase_targets.prf:
../qt/6.5.2/macos/mkspecs/features/exceptions.prf:
../qt/6.5.2/macos/mkspecs/features/yacc.prf:
../qt/6.5.2/macos/mkspecs/features/lex.prf:
Qt-pac-man.pro:
resources.qrc:
../qt/6.5.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../qt/6.5.2/macos/lib/QtGui.framework/Resources/QtGui.prl:
../qt/6.5.2/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Qt-pac-man.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

Qt-pac-man.app/Contents/PkgInfo: 
	@test -d Qt-pac-man.app/Contents || mkdir -p Qt-pac-man.app/Contents
	@$(DEL_FILE) Qt-pac-man.app/Contents/PkgInfo
	@echo "APPL????" > Qt-pac-man.app/Contents/PkgInfo
Qt-pac-man.app/Contents/Info.plist: 
	@test -d Qt-pac-man.app/Contents || mkdir -p Qt-pac-man.app/Contents
	@$(DEL_FILE) Qt-pac-man.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../qt/6.5.2/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,tuhin.Qt-pac-man,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},tuhin.Qt-pac-man,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Qt-pac-man,g" -e "s,@LIBRARY@,Qt-pac-man,g" -e "s,\$${EXECUTABLE_NAME},Qt-pac-man,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >Qt-pac-man.app/Contents/Info.plist

all: Makefile \
		Qt-pac-man.app/Contents/PkgInfo \
		Qt-pac-man.app/Contents/Info.plist Qt-pac-man.app/Contents/MacOS/Qt-pac-man

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents source/game.h source/gameobject.h source/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents source/chasing_strategy.cpp source/game.cpp source/game_object.cpp source/ghost.cpp source/main.cpp source/mainwindow.cpp source/pacman.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Qt-pac-man.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../qt/6.5.2/macos/libexec/rcc \
		game_objects/pacman/c5.png \
		game_objects/pacman/c6.png \
		game_objects/pacman/c3.png \
		game_objects/pacman/d5.png \
		game_objects/pacman/b4.png \
		game_objects/pacman/a6.png \
		game_objects/pacman/d2.png \
		game_objects/pacman/b5.png \
		game_objects/pacman/a1.png \
		game_objects/pacman/d3.png \
		game_objects/pacman/d6.png \
		game_objects/pacman/b3.png \
		game_objects/pacman/d4.png \
		game_objects/pacman/c4.png \
		game_objects/pacman/a2.png \
		game_objects/pacman/c2.png \
		game_objects/pacman/a4.png \
		game_objects/pacman/b2.png \
		game_objects/pacman/a5.png \
		game_objects/pacman/a3.png \
		game_objects/pacman/b6.png \
		game_objects/map_objects/dot.png \
		game_objects/map_objects/power_ball.png \
		game_objects/map_objects/gate.png \
		game_objects/map_objects/dotb.png \
		game_objects/map_objects/map.txt \
		game_objects/map_objects/wall.png \
		game_objects/ghosts/pinkup1.png \
		game_objects/ghosts/greenleft2.png \
		game_objects/ghosts/redup1.png \
		game_objects/ghosts/yellowup1.png \
		game_objects/ghosts/bl1.png \
		game_objects/ghosts/yellowright1.png \
		game_objects/ghosts/yellowleft1.png \
		game_objects/ghosts/yellowright2.png \
		game_objects/ghosts/redright1.png \
		game_objects/ghosts/run.png \
		game_objects/ghosts/redleft1.png \
		game_objects/ghosts/pinkright1.png \
		game_objects/ghosts/pinkup2.png \
		game_objects/ghosts/reddown1.png \
		game_objects/ghosts/pinkdown2.png \
		game_objects/ghosts/pinkleft2.png \
		game_objects/ghosts/yellowup2.png \
		game_objects/ghosts/redleft2.png \
		game_objects/ghosts/greenright2.png \
		game_objects/ghosts/yellowdown1.png \
		game_objects/ghosts/greenleft1.png \
		game_objects/ghosts/pinkleft1.png \
		game_objects/ghosts/redup2.png \
		game_objects/ghosts/yellowdown2.png \
		game_objects/ghosts/bl2.png \
		game_objects/ghosts/greendown2.png \
		game_objects/ghosts/greenup1.png \
		game_objects/ghosts/greenup2.png \
		game_objects/ghosts/pinkright2.png \
		game_objects/ghosts/yellowleft2.png \
		game_objects/ghosts/redright2.png \
		game_objects/ghosts/greenright1.png \
		game_objects/ghosts/greendown1.png \
		game_objects/ghosts/reddown2.png \
		game_objects/ghosts/pinkdown1.png
	/Users/tuhinsaha/Desktop/qt/6.5.2/macos/libexec/rcc -name resources --no-zstd resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_game.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_game.cpp moc_mainwindow.cpp
moc_game.cpp: source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h \
		../qt/6.5.2/macos/libexec/moc
	/Users/tuhinsaha/Desktop/qt/6.5.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/mkspecs/macx-clang -I/Users/tuhinsaha/Desktop/Qt-pac-man-master -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib/QtWidgets.framework/Headers -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib/QtGui.framework/Headers -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib source/game.h -o moc_game.cpp

moc_mainwindow.cpp: source/mainwindow.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../qt/6.5.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		../qt/6.5.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h \
		../qt/6.5.2/macos/libexec/moc
	/Users/tuhinsaha/Desktop/qt/6.5.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/mkspecs/macx-clang -I/Users/tuhinsaha/Desktop/Qt-pac-man-master -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib/QtWidgets.framework/Headers -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib/QtGui.framework/Headers -I/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/tuhinsaha/Desktop/qt/6.5.2/macos/lib source/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../qt/6.5.2/macos/libexec/uic
	/Users/tuhinsaha/Desktop/qt/6.5.2/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

game.o: source/game.cpp source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QString \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QFile \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qfile.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QRandomGenerator \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qrandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o source/game.cpp

game_object.o: source/game_object.cpp source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game_object.o source/game_object.cpp

ghost.o: source/ghost.cpp source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h \
		source/chasing_strategy.cpp \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QRandomGenerator \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qrandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ghost.o source/ghost.cpp

main.o: source/main.cpp source/mainwindow.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../qt/6.5.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		../qt/6.5.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QApplication \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o source/main.cpp

mainwindow.o: source/mainwindow.cpp source/mainwindow.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../qt/6.5.2/macos/lib/QtGui.framework/Headers/QKeyEvent \
		../qt/6.5.2/macos/lib/QtGui.framework/Headers/qevent.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o source/mainwindow.cpp

pacman.o: source/pacman.cpp source/game.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsView \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../qt/6.5.2/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QTimer \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QPair \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qpair.h \
		source/gameobject.h \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/QVector \
		../qt/6.5.2/macos/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pacman.o source/pacman.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Qt-pac-man/bin || mkdir -p $(INSTALL_ROOT)/opt/Qt-pac-man/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Qt-pac-man/bin/Qt-pac-man.app
	
	$(QINSTALL) Qt-pac-man.app $(INSTALL_ROOT)/opt/Qt-pac-man/bin/Qt-pac-man.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Qt-pac-man/bin/Qt-pac-man.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Qt-pac-man/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

